FROM jenkins/jenkins:lts

USER root

# Install Docker + kubectl + curl
RUN apt-get update && \
    apt-get install -y docker.io curl && \
    curl -LO https://dl.k8s.io/release/v1.29.0/bin/linux/amd64/kubectl && \
    install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl && \
    rm kubectl && \
    apt-get clean

USER jenkins