apiVersion: v1
kind: Service
metadata:
  name: spring-devops4-service
spec:
  selector:
    app: spring-devops4
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
